#!/usr/bin/env python3
"""
Generates the result tables of the paper from the raw CSVs in results/.
Every published table is regenerated by this script, so the numbers in
the text stay pinned to the data. Output goes to paper/tables/*.tex,
included via \\input in experiments.tex.

  tab_q1_boundary.tex  Q1 boundary extension (solved counts and medians per n x k*)
  tab_q2_codes.tex     comparison of the three codes on the controlled family
  tab_q3_groups.tex    per-group benchmark summary (k*, gap, time, optima, rho)
  tab_q3_mediation.tex per-group conditional association coefficients (k*, terminal gap, root
                       gap and nodes) with bootstrap intervals
  tab_reductions.tex   static summary of the covering constructions (committed
                       alongside the generated tables; not derived from the CSVs)

Usage: python3 scripts/make_paper_tables.py
"""
import csv, math, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RES  = os.path.join(ROOT, "results")
OUT  = os.path.join(ROOT, "paper", "tables")
os.makedirs(OUT, exist_ok=True)

def load(name):
    with open(os.path.join(RES, name), newline="") as fh:
        return list(csv.DictReader(fh))

def median(xs):
    s = sorted(xs); n = len(s)
    if n == 0: return float("nan")
    return s[n//2] if n % 2 else 0.5*(s[n//2-1]+s[n//2])

def rankdata(a):
    order = sorted(range(len(a)), key=lambda i: a[i]); r=[0.0]*len(a); i=0
    while i < len(a):
        j = i
        while j+1 < len(a) and a[order[j+1]] == a[order[i]]: j += 1
        avg = (i+j)/2.0+1.0
        for k in range(i, j+1): r[order[k]] = avg
        i = j+1
    return r

def spearman(x, y):
    rx, ry = rankdata(x), rankdata(y); n=len(x)
    mx, my = sum(rx)/n, sum(ry)/n
    sx = math.sqrt(sum((v-mx)**2 for v in rx)); sy = math.sqrt(sum((v-my)**2 for v in ry))
    return sum((rx[i]-mx)*(ry[i]-my) for i in range(n))/(sx*sy)

def perm_p(x, y, nperm=20000, seed=20260718):
    """Two-sided permutation p-value of the Spearman with mid-ranks.
    Fixed seed, so the published number is deterministic."""
    import random as _rnd
    rng = _rnd.Random(seed)
    obs = spearman(x, y); cnt = 0; y2 = list(y)
    for _ in range(nperm):
        rng.shuffle(y2)
        if abs(spearman(x, y2)) >= abs(obs) - 1e-12:
            cnt += 1
    return (cnt + 1) / (nperm + 1)

def boot_ci(x, y, nboot=10000, seed=20260719):
    """Percentile bootstrap 95% CI of the Spearman coefficient, fixed seed (pinned number)."""
    import random as _rnd
    rng = _rnd.Random(seed)
    n = len(x); vals = []
    for _ in range(nboot):
        idx = [rng.randrange(n) for _ in range(n)]
        bx = [x[i] for i in idx]; by = [y[i] for i in idx]
        if len(set(bx)) < 2 or len(set(by)) < 2:
            continue
        vals.append(spearman(bx, by))
    vals.sort()
    lo = vals[int(0.025 * len(vals))]
    hi = vals[int(0.975 * len(vals)) - 1]
    return lo, hi

def round_half_up(v, nd=2):
    from decimal import Decimal, ROUND_HALF_UP
    return str(Decimal(repr(v)).quantize(Decimal("0."+"0"*nd), rounding=ROUND_HALF_UP))

# ---------------------------------------------------------------- Q1 boundary
q1 = load("q1_xp.csv")
# 60 s boundary extension: the 60 runs with nK=30 and nL=3 (the main grid uses
# nK in {50,100} and nL in {5,10}); 600 s budget family: 10 seeds per cell over
# the same grid (results/q1_boundary600.csv)
bnd = [r for r in q1 if r["nK"] == "30" and r["nL"] == "3"]
b600 = load("q1_boundary600.csv")
ns   = sorted({int(r["nI"])+int(r["nJ"]) for r in bnd} |
              {int(r["nI"])+int(r["nJ"]) for r in b600})
kts  = [4, 8, 12, 16]
def cell_tex(cell, solved):
    if not cell:
        return "--"
    if solved:
        med = median([float(r["time"]) for r in solved])
        star = r"$^{\star}$" if len(solved) < 3 else ""
        return f"{len(solved)}/{len(cell)} ({med:.1f}){star}"
    return f"0/{len(cell)}"
# The middle row of each block reclassifies the ten-seed 600 s sample by the
# recorded time (deterministic single-thread code), so the 60-versus-600
# contrast is read on the same instances and does not confound budget with
# seeds. The nearest recorded solve time is more than seven seconds from the
# 60 s threshold, so the reclassification is stable.
rows_tex = []
SPECS = (("$60$", bnd, lambda r: r["kstar_target"], None),
         ("$60$ (ten-seed)", b600, lambda r: str(2*int(r["tI"])), 60.0),
         ("$600$", b600, lambda r: str(2*int(r["tI"])), None))
for n in ns:
    for label, pool, tsel, cap in SPECS:
        cells = []
        for kt in kts:
            cell = [r for r in pool if int(r["nI"])+int(r["nJ"]) == n
                    and tsel(r) == str(kt)]
            solved = [r for r in cell if r["status"] == "OPTIMAL"
                      and r["timeout"] == "0"
                      and (cap is None or float(r["time"]) <= cap)]
            cells.append(cell_tex(cell, solved))
        head = f"${n}$" if label == "$60$" else ""
        rows_tex.append(f"{head} & {label} & " + " & ".join(cells) + r" \\")
    rows_tex.append(r"\addlinespace[2pt]")
rows_tex = rows_tex[:-1]
with open(os.path.join(OUT, "tab_q1_boundary.tex"), "w") as fh:
    fh.write(
r"""\begin{table}[H]
\centering
\caption{The boundary extension of Q1 as a function of the budget. Each
cell reports solved over attempted instances at the given $n=|I|+|J|$,
budget and covering-bound target $k^\ast$, with the median time in
seconds of the solved runs in parentheses. The $60$~s rows use the
three-seed boundary extension. The ten-seed rows both draw on the
$600$~s budget sample, the middle row counting a run as solved under
$60$~s exactly when its recorded time is at most $60$~s, which the
deterministic single-threaded code permits, so the budget contrast of
the last two rows compares the same instances and only the budget
varies. The tenfold budget displaces the
partially solved band from $n=24$ to $n=28$, where the solved count
again rises with the bound, and $n=40$ stays fully censored. Starred
cells have fewer than three solved runs, so their medians rest on one
or two observations.}
\label{tab:q1boundary}
\setlength{\tabcolsep}{3.2pt}
\begin{tabular}{llcccc}
\hline
$n$ & budget (s) & $k^\ast=4$ & $k^\ast=8$ & $k^\ast=12$ & $k^\ast=16$ \\
\hline
""" + "\n".join(rows_tex) + "\n" + r"""\hline
\end{tabular}
\end{table}
""")

# ---------------------------------------------------------------- Q2 codes
ctrl_mip = load("controlled_mip.csv")
ctrl_bd  = load("controlled_bd.csv")
main_xp  = [r for r in q1 if not (r["nK"] == "30" and r["nL"] == "3")]
xp_solved  = [r for r in main_xp if r["status"] == "OPTIMAL" and r["timeout"] == "0"]
mip_solved = [r for r in ctrl_mip if r["status"] == "OPTIMAL"]
bd_solved  = [r for r in ctrl_bd  if r["status"] == "OPTIMAL"]
def fmt_med(rs, key):
    if not rs: return "--"
    return round_half_up(median([float(r[key]) for r in rs]))
lines = [
    r"\textsc{Xp} & $60$ & $%d/%d$ & %s \\" % (len(xp_solved), len(main_xp),
        fmt_med(xp_solved, "time")),
    r"\textsc{Mip} & $600$ & $%d/%d$ & %s \\" % (len(mip_solved), len(ctrl_mip),
        fmt_med(mip_solved, "solver_time_s")),
    r"\textsc{Bd} & $600$ & $%d/%d$ & %s \\" % (len(bd_solved), len(ctrl_bd),
        fmt_med(bd_solved, "solver_time_s")),
]
with open(os.path.join(OUT, "tab_q2_codes.tex"), "w") as fh:
    fh.write(
r"""\begin{table}[H]
\centering
\caption{The three exact codes on the $400$-instance main grid of the
controlled family, whose graphs all have $n\ge 40$. Solved means proven
optimal within the per-code limit. The median time is over solved runs
only, in seconds. \textsc{Mip} closes every instance the enumeration
leaves censored, the empirical face of the regime border of Q1. The
enumeration ran on a different machine from the two integer programming
codes, which shared one machine, so times compare only within a code
and between \textsc{Mip} and \textsc{Bd}, and the cross-code reading
is the solved-versus-censored contrast.}
\label{tab:q2codes}
\begin{tabular}{lccc}
\hline
code & limit (s) & solved & median time (s) \\
\hline
""" + "\n".join(lines) + "\n" + r"""\hline
\end{tabular}
\end{table}
""")

# ---------------------------------------------------------------- Q3 groups
kstar = {r["instance"]: int(r["kstar_py"]) for r in load("mauri_kstar.csv")}
mauri = load("mauri_mip.csv")
def group_of(name):
    p = name.split("-")
    return f"{p[2]}-{p[3].split('.')[0]}"
groups = {}
for r in mauri:
    key = r["instance"] + ".txt" if r["instance"] + ".txt" in kstar else r["instance"]
    groups.setdefault(group_of(r["instance"]), []).append(
        (kstar[key], float(r["gap"]) * 100.0, float(r["solver_time_s"]),
         r["status"] == "OPTIMAL"))
order = ["50-5", "50-10", "100-5", "100-10"]
stats, pooled_k, pooled_g = [], [], []
for g in order:
    v = groups[g]
    ks = [a for a, _, _, _ in v]; gaps = [b for _, b, _, _ in v]
    nopt = sum(1 for *_, o in v if o)
    rho = spearman(ks, gaps); p = perm_p(ks, gaps)
    lo, hi = boot_ci(ks, gaps)
    pooled_k += ks; pooled_g += gaps
    stats.append([g, v, ks, gaps, nopt, rho, p, lo, hi])
pooled = spearman(pooled_k, pooled_g)
pooled_p = perm_p(pooled_k, pooled_g)
# Holm correction over the five gap tests (four groups + pooled)
tests = [(st[0], st[6]) for st in stats] + [("pooled", pooled_p)]
srt = sorted(tests, key=lambda t: t[1]); m = len(srt); prev = 0.0; adj = {}
for i, (name, p) in enumerate(srt):
    a_ = min(1.0, max(prev, (m - i) * p)); prev = a_; adj[name] = a_
lines = []
for g, v, ks, gaps, nopt, rho, p, lo, hi in stats:
    lines.append(
        f"${g.split('-')[0]}$-${g.split('-')[1]}$ & ${len(v)}$ & "
        f"${min(ks)}$/${int(median(ks))}$/${max(ks)}$ & "
        f"${median(gaps):.1f}$ & ${nopt}$ & "
        f"${rho:+.2f}$ [${lo:+.2f}$, ${hi:+.2f}$] & "
        f"${adj[g]:.3f}$ " + chr(92)*2)
with open(os.path.join(OUT, "tab_q3_groups.tex"), "w") as fh:
    fh.write(
r"""\begin{table}[H]
\centering
\caption{The benchmark campaign by size group, $3{,}600$~s per instance.
Columns give the group $|I|$-$|L|$, the instance count, the minimum,
median and maximum of the covering bound $k^\ast$, the median terminal
gap in percent, the number of proven optima, the within-group Spearman
correlation between $k^\ast$ and the terminal gap, and its
Holm-adjusted two-sided permutation $p$-value. Correlations carry
percentile bootstrap $95\%%$ confidence intervals in brackets. Each
interval describes one group alone, and the within-group column is the
sharper instrument, the pooled value mixing the group effect with size.
The pooled correlation over all $100$ instances is $%.2f$,
Holm-adjusted $p=%.3f$.}
\label{tab:q3groups}
\small
\setlength{\tabcolsep}{4pt}
\begin{tabular}{lcccccc}
\hline
group & $\#$ & $k^\ast$ min/med/max & gap (\%%) & opt.\ &
$\rho$ [$95\%%$ CI] & $p$ \\
\hline
""" % (pooled, adj["pooled"]) + "\n".join(lines) + "\n" + r"""\hline
\end{tabular}
\end{table}
""")

# ------------------------------------------------------------- Q3 mediation
# Same 100 benchmark runs, now joined with the root relaxation and the node
# count extracted from the stored Gurobi logs. The partial coefficient is the
# Spearman correlation of k* with the terminal gap once the root gap is held
# fixed, computed as the Pearson correlation of the two rank residuals.
def partial_sp(x, y, z):
    a, b, c = spearman(x, y), spearman(x, z), spearman(y, z)
    den = (1.0 - b*b) * (1.0 - c*c)
    return (a - b*c) / math.sqrt(den) if den > 1e-12 else float("nan")

def resid_ranks(v, z):
    rv, rz = rankdata(v), rankdata(z)
    n = len(rv); mv, mz = sum(rv)/n, sum(rz)/n
    szz = sum((t-mz)**2 for t in rz)
    beta = sum((rz[i]-mz)*(rv[i]-mv) for i in range(n)) / szz if szz > 0 else 0.0
    return [rv[i] - (mv + beta*(rz[i]-mz)) for i in range(n)]

def pearson(x, y):
    n = len(x); mx, my = sum(x)/n, sum(y)/n
    sx = math.sqrt(sum((v-mx)**2 for v in x)); sy = math.sqrt(sum((v-my)**2 for v in y))
    if sx == 0 or sy == 0: return float("nan")
    return sum((x[i]-mx)*(y[i]-my) for i in range(n))/(sx*sy)

def perm_p_partial(x, y, z, strata=None, nperm=20000, seed=20260718):
    """Freedman-Lane residual permutation test for the partial coefficient,
    fixed seed. Both variables are rank-regressed on the conditioning
    variable and the residuals of the second are permuted, within strata
    when a stratum label list is given (used for the pooled column, where
    permutations run inside each size group)."""
    import random as _rnd
    rx, ry = resid_ranks(x, z), resid_ranks(y, z)
    obs = pearson(rx, ry); rng = _rnd.Random(seed); cnt = 0; yy = list(ry)
    n = len(yy)
    pos = [list(range(n))] if strata is None else           [[i for i in range(n) if strata[i] == g] for g in sorted(set(strata))]
    for _ in range(nperm):
        for ps in pos:
            vals = [yy[i] for i in ps]
            rng.shuffle(vals)
            for i, v in zip(ps, vals):
                yy[i] = v
        if abs(pearson(rx, yy)) >= abs(obs) - 1e-12:
            cnt += 1
    return (cnt + 1) / (nperm + 1)

def boot_ci_stat(stat, data, nboot=10000, seed=20260719):
    """Percentile bootstrap over instances for any statistic of the sample."""
    import random as _rnd
    rng = _rnd.Random(seed); n = len(data); vals = []
    for _ in range(nboot):
        s = [data[rng.randrange(n)] for _ in range(n)]
        try:
            v = stat(s)
        except ZeroDivisionError:
            continue  # degenerate resample with a constant column
        if v == v:
            vals.append(v)
    vals.sort()
    return vals[int(0.025*len(vals))], vals[int(0.975*len(vals))-1]

rootrows = {r["instance"]: r for r in load("mauri_rootgap.csv")}
med_rows = {}
for r in mauri:
    rr = rootrows[r["instance"]]
    obj, rlp = float(rr["obj"]), float(rr["root_lp"])
    med_rows.setdefault(group_of(r["instance"]), []).append(
        (kstar[r["instance"] + ".txt" if r["instance"] + ".txt" in kstar else r["instance"]],
         float(r["gap"])*100.0, (obj - rlp)/obj*100.0, float(rr["nodes"])))
col = lambda s, i: [t[i] for t in s]
STATS = [(r"$\rho(k^\ast,\ \text{gap})$",       lambda s: spearman(col(s,0), col(s,1))),
         (r"$\rho(k^\ast,\ \text{root gap})$",  lambda s: spearman(col(s,0), col(s,2))),
         (r"$\rho(\text{gap},\ \text{root gap})$", lambda s: spearman(col(s,1), col(s,2))),
         (r"$\rho(k^\ast,\ \text{gap}\mid\text{root gap})$",
          lambda s: partial_sp(col(s,0), col(s,1), col(s,2))),
         (r"$\rho(k^\ast,\ \text{nodes})$",     lambda s: spearman(col(s,0), col(s,3)))]
mcols = order + ["pooled"]
msample = {g: (med_rows[g] if g != "pooled" else [t for g2 in order for t in med_rows[g2]])
           for g in mcols}
mvals = {(g, i): st(msample[g]) for g in mcols for i, (_, st) in enumerate(STATS)}
mci   = {(g, i): boot_ci_stat(st, msample[g]) for g in mcols for i, (_, st) in enumerate(STATS)}
pooled_strata = [g2 for g2 in order for _ in med_rows[g2]]
praw  = {g: perm_p_partial(col(msample[g],0), col(msample[g],1), col(msample[g],2),
                           strata=(pooled_strata if g == "pooled" else None))
         for g in mcols}
srt = sorted(praw.items(), key=lambda t: t[1]); m = len(srt); prev = 0.0; padj = {}
for i, (g, p) in enumerate(srt):
    a_ = min(1.0, max(prev, (m - i) * p)); prev = a_; padj[g] = a_
mlines = []
for i, (lab, _) in enumerate(STATS):
    mlines.append(lab + " & " +
                  " & ".join("$%+.2f$" % mvals[(g, i)] for g in mcols) + r" \\")
    mlines.append(" & " + " & ".join(
        r"{\scriptsize [$%+.2f$, $%+.2f$]}" % mci[(g, i)] for g in mcols) + r" \\[2pt]")
mlines.append(r"adjusted $p$ (partial) & " +
              " & ".join("$%.3f$" % padj[g] for g in mcols) + r" \\")
with open(os.path.join(OUT, "tab_q3_mediation.tex"), "w") as fh:
    fh.write(
r"""\begin{table}[H]
\centering
\caption{Conditional association coefficients on the $100$ benchmark runs, by
size group and pooled. Rows give the Spearman correlation of the covering
bound with the terminal gap, of the bound with the root relaxation gap, of the
two gaps with each other, the partial rank correlation of the bound with the
terminal gap at fixed root gap, and the correlation of the bound with the
explored node count. The partial coefficient is the Pearson correlation of the
residuals of the two rank-on-rank regressions on the root-gap ranks, and the
pooled column conditions on the root gap only, not on the group. Brackets hold
percentile bootstrap $95\%$ confidence intervals over
$10{,}000$ resamples of the instances (seed $20260719$), not adjusted for
multiplicity and drawn without stratification, so the pooled interval
retains the group-composition component that the within-group
permutation removes. The last row reports the Holm-adjusted
two-sided $p$-value of the partial coefficient from a Freedman--Lane residual
permutation test with $20{,}000$ permutations (seed $20260718$), permutations
running within each size group in the pooled column. In the two
hundred-factory groups the two gaps correlate at $0.99$
or above, so barely one per cent of the rank variance of the terminal gap
survives conditioning and the partial coefficient in those columns rests on
very little, which its wide interval records.}
\label{tab:q3mediation}
\small
\setlength{\tabcolsep}{3pt}
\begin{tabular}{lccccc}
\hline
 & $50$-$5$ & $50$-$10$ & $100$-$5$ & $100$-$10$ & pooled \\
\hline
""" + "\n".join(mlines) + "\n" + r"""\hline
\end{tabular}
\end{table}
""")

print("tables written to paper/tables/")
for f in sorted(os.listdir(OUT)):
    print(" ", f)
